In [1]:
import torch

In [2]:
import sklearn

In [3]:
import numpy as np

In [7]:
# torch.cuda.is_available()
# torch.cuda.get_device_name()
# nvidia-smi

## Torch Tutorial

In [8]:
# tensor
# generate a all 0 tensor
torch.Tensor(5, 4)

tensor([[1.0745e-38, 1.0102e-38, 9.7347e-39, 9.2755e-39],
        [5.9694e-39, 8.9082e-39, 1.0194e-38, 9.1837e-39],
        [4.6837e-39, 9.2755e-39, 1.0837e-38, 8.4490e-39],
        [1.1112e-38, 1.0194e-38, 9.0919e-39, 8.7245e-39],
        [1.0286e-38, 8.4490e-39, 9.6429e-39, 8.4490e-39]])

In [9]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
b = torch.Tensor(a)
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [11]:
b.size()

torch.Size([2, 3])

In [12]:
c = torch.rand(5,4)
c

tensor([[0.1392, 0.9092, 0.8512, 0.3312],
        [0.9922, 0.9789, 0.1043, 0.6765],
        [0.7480, 0.3812, 0.3751, 0.8673],
        [0.1272, 0.7889, 0.7272, 0.3554],
        [0.5200, 0.0947, 0.9275, 0.7376]])

In [13]:
d = torch.Tensor([[1,2],[3,4],[5,6]])
d

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [14]:
a_ = torch.Tensor(a) # will set the elements in a to be float32
a__ = torch.from_numpy(a) # will follow the origin element format, like int

In [15]:
a_ == a__

tensor([[True, True, True],
        [True, True, True]])

In [16]:
a_.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [17]:
a__.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
x = torch.rand(5, 4)
y = torch.rand(5, 4)

In [19]:
x + y

tensor([[0.0723, 1.3698, 1.8038, 1.6774],
        [0.7032, 0.8377, 0.7034, 1.0002],
        [0.4996, 0.4701, 1.1440, 1.0316],
        [0.9887, 0.5133, 0.7189, 0.8580],
        [1.1993, 1.1984, 0.4199, 0.9584]])

In [20]:
x * y # multiply two elements in each position

tensor([[0.0008, 0.4688, 0.8050, 0.6991],
        [0.1146, 0.1236, 0.0032, 0.1222],
        [0.0411, 0.0365, 0.2643, 0.2658],
        [0.2411, 0.0631, 0.1287, 0.1826],
        [0.2859, 0.2786, 0.0183, 0.0339]])

In [21]:
x.add(y)

tensor([[0.0723, 1.3698, 1.8038, 1.6774],
        [0.7032, 0.8377, 0.7034, 1.0002],
        [0.4996, 0.4701, 1.1440, 1.0316],
        [0.9887, 0.5133, 0.7189, 0.8580],
        [1.1993, 1.1984, 0.4199, 0.9584]])

In [22]:
x

tensor([[0.0581, 0.7006, 0.9937, 0.7733],
        [0.2566, 0.6465, 0.6988, 0.1424],
        [0.3956, 0.0981, 0.3212, 0.5297],
        [0.5515, 0.3093, 0.3819, 0.4671],
        [0.3282, 0.3156, 0.0495, 0.9216]])

In [23]:
x.add_(y)

tensor([[0.0723, 1.3698, 1.8038, 1.6774],
        [0.7032, 0.8377, 0.7034, 1.0002],
        [0.4996, 0.4701, 1.1440, 1.0316],
        [0.9887, 0.5133, 0.7189, 0.8580],
        [1.1993, 1.1984, 0.4199, 0.9584]])

In [24]:
x

tensor([[0.0723, 1.3698, 1.8038, 1.6774],
        [0.7032, 0.8377, 0.7034, 1.0002],
        [0.4996, 0.4701, 1.1440, 1.0316],
        [0.9887, 0.5133, 0.7189, 0.8580],
        [1.1993, 1.1984, 0.4199, 0.9584]])

In [25]:
from torch.autograd import Variable

In [26]:
x = Variable(torch.Tensor([3]), requires_grad=True)
y = Variable(torch.Tensor([4]), requires_grad=True)

In [27]:
hasattr(x, "data")

True

In [28]:
hasattr(x, "grad")

True

In [29]:
hasattr(x, "creator")

False

In [30]:
x = Variable(torch.Tensor([3]), requires_grad=True)
y = Variable(torch.Tensor([4]), requires_grad=True)
z = 5 * x + 4 * y

In [31]:
z.backward()

In [32]:
x.grad, y.grad

(tensor([5.]), tensor([4.]))

In [33]:
# print(dir(z))

In [34]:
x.grad

tensor([5.])

In [35]:
x.grad.data.data.data.data

tensor([5.])

In [37]:
x.grad.item() # only one element can be fetch

5.0

In [38]:
type(x.grad)

torch.Tensor

In [39]:
type(x.grad.data)

torch.Tensor

In [40]:
y.grad

tensor([4.])

In [41]:
## torch neural network 
from torch import nn

In [42]:
# dir(nn) # check all the related layers 

In [43]:
import torch.nn.functional as F

In [44]:
#dir(F) # check all the functional layers

In [45]:
class net_name(nn.Module):
    def __init__(self):
        super(net_name, self).__init__()
        # 可以添加各种网络层
        self.conv1 = nn.Conv2d(3, 10, 3)
        # 具体每种层的参数可以去查看文档
        
    def forward(self, x):
        # 定义向前传播
        out = self.conv1(x)
        return out